import { Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import localFont from 'next/font/local';
import Footer from "@/Components/Footer";


const orbitron = Orbitron({
  subsets: ["latin"], // Ensures proper language support
  weight: ["400", "700"], // Specify font weights
  variable: "--font-orbitron", // Custom CSS variable
});
export const metadata = {
  title: "Evzonetech | Software Testing & Quality Assurance",
  description: "Generated by Evezone",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={orbitron.variable}>
      
      <body className="font-orbitron">
        <Navbar/>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
